//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flakysalt.CharacterKeybinds.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsLoca {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsLoca() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("flakysalt.CharacterKeybinds.Resources.SettingsLoca", typeof(SettingsLoca).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arenanet Macro Policy.
        /// </summary>
        internal static string anetMacroPolicyButton {
            get {
                return ResourceManager.GetString("anetMacroPolicyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts how fast the keybindings will be applied.\nLower (Left) this if your system is weaker and has trouble applying the keybindings..
        /// </summary>
        internal static string autoClickSpeedMultiplierHint {
            get {
                return ResourceManager.GetString("autoClickSpeedMultiplierHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keybindings Apply Speed.
        /// </summary>
        internal static string autoClickSpeedMultiplierSetting {
            get {
                return ResourceManager.GetString("autoClickSpeedMultiplierSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically change keybinds when switching elite specializations on the same character..
        /// </summary>
        internal static string changeKeybindsOnSpecSwitchHint {
            get {
                return ResourceManager.GetString("changeKeybindsOnSpecSwitchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change keybinds When Switching Specialization.
        /// </summary>
        internal static string changeKeybindsOnSpecSwitchSetting {
            get {
                return ResourceManager.GetString("changeKeybindsOnSpecSwitchSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help / FAQ.
        /// </summary>
        internal static string helpFaqButton {
            get {
                return ResourceManager.GetString("helpFaqButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the Keybinds folder.\nIf you dont know where this is, export your keybinds via the GW2 ingame menu and the location is shown in the ingame chat.
        /// </summary>
        internal static string keybindsDirectoryHint {
            get {
                return ResourceManager.GetString("keybindsDirectoryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keybinds Folder Path.
        /// </summary>
        internal static string keybindsDirectorySetting {
            get {
                return ResourceManager.GetString("keybindsDirectorySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options Menu Keybind.
        /// </summary>
        internal static string optionsMenuKeybindsSetting {
            get {
                return ResourceManager.GetString("optionsMenuKeybindsSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a Bug.
        /// </summary>
        internal static string reportBugButton {
            get {
                return ResourceManager.GetString("reportBugButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide the corner icon to open the keybinds window..
        /// </summary>
        internal static string showCornerIconHint {
            get {
                return ResourceManager.GetString("showCornerIconHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show corner icon.
        /// </summary>
        internal static string showCornerIconSetting {
            get {
                return ResourceManager.GetString("showCornerIconSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troubleshoot.
        /// </summary>
        internal static string troubleshootButton {
            get {
                return ResourceManager.GetString("troubleshootButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switching to default keybinds when no others are defined for a character or specialization..
        /// </summary>
        internal static string useDefaultKeybindsHint {
            get {
                return ResourceManager.GetString("useDefaultKeybindsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Default Keybinds.
        /// </summary>
        internal static string useDefaultKeybindsSetting {
            get {
                return ResourceManager.GetString("useDefaultKeybindsSetting", resourceCulture);
            }
        }
    }
}
