//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flakysalt.CharacterKeybinds.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TutorialLoca {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TutorialLoca() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("flakysalt.CharacterKeybinds.Resources.TutorialLoca", typeof(TutorialLoca).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string closeButtonText {
            get {
                return ResourceManager.GetString("closeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Setup Tutorial.
        /// </summary>
        internal static string initialSetupHeader {
            get {
                return ResourceManager.GetString("initialSetupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Character Keybinds!
        ///
        ///If you have not done so already, please provide an API key to Blish HUD..
        /// </summary>
        internal static string initialSetupPanel1 {
            get {
                return ResourceManager.GetString("initialSetupPanel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To set up your Guild Wars 2 keybinds, go to your settings menu and then to the Control Options Tab.
        ///
        ///In here, press the Export button at the bottom of the page.
        ///
        ///This will save your current keybindings to be used in the module..
        /// </summary>
        internal static string initialSetupPanel2 {
            get {
                return ResourceManager.GetString("initialSetupPanel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat this step for every unique set of keybinds you want to create.
        ///
        ///You can also repeat this step at any time in the future..
        /// </summary>
        internal static string initialSetupPanel3 {
            get {
                return ResourceManager.GetString("initialSetupPanel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now you can open the module itself from the top left of your screen. 
        ///
        ///Here you can specify your default keybinds, which will be used 
        ///for all characters and specializations that have no keybinds assigned in this menu.
        ///
        ///Below, you can specify keybinds per character or specialization..
        /// </summary>
        internal static string initialSetupPanel4 {
            get {
                return ResourceManager.GetString("initialSetupPanel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any questions or suggestions,
        ///you can find the FAQ and other useful functions 
        ///at the bottom of the module settings page.
        ///
        ///Feel free to reach out to me directly on the Blish HUD Discord server for further support &lt;3.
        /// </summary>
        internal static string initialSetupPanel5 {
            get {
                return ResourceManager.GetString("initialSetupPanel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string nextButtonText {
            get {
                return ResourceManager.GetString("nextButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string previousButtonText {
            get {
                return ResourceManager.GetString("previousButtonText", resourceCulture);
            }
        }
    }
}
